name: Job Output
on:
    workflow_dispatch:
#   push:
#     branches:
#       - master
        inputs:
            environment: 
             description: 'Enter name'
             required: true
             default: 'rishit'
jobs:
    job1:
      name: job1
      runs-on: ubuntu-latest
      outputs:
        job1_name: ${{steps.set-output.outputs.name}}
      steps:
        - name: set output
          id: set-output
          run: echo "name=${{github.event.inputs.environment}}" >> $GITHUB_OUTPUT

        - name: Access output
          run: echo "value is ${{steps.set-output.outputs.name}}"

    job2:
      name: job2
      runs-on: ubuntu-latest
      needs: job1
      steps:
        - name: Access output
          run: echo "value of output from job1 is ${{needs.job1.outputs.job1_name}}"   