name: Build Angular app

on:
  push:
    branches:
      - master
jobs:
    job1:
      name: job1
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2

      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
         node-version: 18.x


      - name: Install Dependencies
        run: npm i -g -D supertest mocha chai
    #   - run: npm ci
      - run: npm run build --if-present
      - run: npm run test

    #   - name: Build
    #     run: npm run build

      - name: upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist
    
    # job2:
    #   runs-on: ubuntu-latest
    #   needs: job1
    #   steps:
    #   - name: Download artifact
    #     uses: actions/download-artifact@v4
    #     with: 
    #       name: build-artifact
    #       path: artifact  #create this dir and add artifact in this dir.